// APPLICATION
export const FETCH_APPLICATION_PROFILE = "FETCH_APPLICATION_PROFILE";
export const FETCH_APPLICATION_PROFILE_SUCCESS =
  "FETCH_APPLICATION_PROFILE_SUCCESS";
export const FETCH_APPLICATION_PROFILE_FAILURE =
  "FETCH_APPLICATION_PROFILE_FAILURE";
export const APP_SET_ONLINE = "APP_SET_OFFLINE";

