
// ACCOUNT
export const FETCH_ACCOUNT = "FETCH_ACCOUNT";
export const FETCH_ACCOUNT_SUCCESS = "FETCH_ACCOUNT_SUCCESS";
export const FETCH_ACCOUNT_FAILURE = "FETCH_ACCOUNT_FAILURE";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const RESET_ME = "RESET_ME";

export const ME_FROM_TOKEN = "ME_FROM_TOKEN";
export const ME_FROM_TOKEN_SUCCESS = "ME_FROM_TOKEN_SUCCESS";
export const ME_FROM_TOKEN_FAILURE = "ME_FROM_TOKEN_FAILURE";

export const UPDATE_USER_DATA = "UPDATE_USER_DATA";

// APPLICATION
export const FETCH_APPLICATION_PROFILE = "FETCH_APPLICATION_PROFILE";
export const FETCH_APPLICATION_PROFILE_SUCCESS =
  "FETCH_APPLICATION_PROFILE_SUCCESS";
export const FETCH_APPLICATION_PROFILE_FAILURE =
  "FETCH_APPLICATION_PROFILE_FAILURE";
export const APP_SET_ONLINE = "APP_SET_OFFLINE";

